const GET_DATA = 'GET_DATA';
const SET_PRODUCT_CART = 'SET_PRODUCT_CART';
const SET_PRODUCT_FAVORITE = 'SET_PRODUCT_FAVORITE';
const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';

export default {
    GET_DATA,
    SET_PRODUCT_CART,
    SET_PRODUCT_FAVORITE,
    REMOVE_PRODUCT_CART
}